package com.yelloco.ticketlibrary;

public enum  HtmlIDs
{
    CTLS_LOGO("ctls_logo"),
    CUSTOMER_OR_MERCHANT_VERSION("customer_or_merchant_version"),
    MERCHANT_NAME("merchant_name"),
    MERCHANT_ADDRESS("merchant_address"),
    MERCHANT_LABEL("merchant_label"),
    MERCHANT_NUMBER("merchant_number"),
    TERMINAL_LABEL("terminal_label"),
    RRN_LABEL("rrn_label"),
    RRN_NUMBER("rrn_number"),
    AUTH_number("authorization_number"),
    TERMINAL_ID("terminal_id"),
    CARD_NUMBER("card_number"),
    BATCH_LABEL("batch_label"),
    BATCH_NUMBER("batch_code"),
    RECEIPT_LABEL("receipt_label"),
    RECEIPT_NUMBER("receipt_number"),
    TERMINAL_STATUS_INDICATOR("terminal_status_indicator"),
    APPLICATION_NAME("application_name"),
    APPLICATION_ID_VALUE("application_id_value"),
    PREAUTH_LABEL("pre_authorization_label"),
    REFUND_LABEL("refund_label"),
    DENIED_LABEL("denied_label"),
    CONFIRMATIONS_LABEL("confirmations_label"),
    CARD_HOLDER_NAME("card_holder_name"),
    CARD_EXPIRATION_DATE("card_expiration_date"),
    OPERATION_TYPE("operation_type"),
    AUTHORIZATION_CODE("authorization_code"),
    ACCEPTED_TRANSACTION("accepted_transaction"),
    SIGN_BELOW("please_sign_below"),
    ONLINE_PIN("online_pin_entered"),
    CREDIT_DEBIT_LABEL("credit_debit_label"),
    ORDER_LABEL("order_label"),
    ORDER_NUMBER("order_number"),
    APP_SECTION("APP_SECTION"),
    CURRENCY_LABEL_OPERATIONS("currency"),
    DATE_LABEL("date_label"),
    TRANSACTION_DATE("transaction_date"),
    TIME_LABEL("time_label"),
    TRANSACTION_TIME("transaction_time"),
    TRANSACTION_AMOUNT("transaction_amount"),
    CURRENCY("currency"),
    OPERATION("op"),
    EMV_SECTION("emv_section"),
    TICKET_LABEL("ticket_label"),
    APPLICATION_LABEL("application_label"),
    APPLICATION_ID("application_id"),
    NUMBER_OF_TRANSACTION("number_of_transaction"),
    AUTHORIZATION_RESPONSE_CODE("authorization_response_code"),
    TERMINAL_VERIFICATION_RESULT("terminal_verification_result"),
    DCC_SECTION_PART_ONE("dcc_section_part_one"),
    DCC_SECTION_PART_TWO("dcc_section_part_two"),
    LITERALLINLITTRANS("LiteralLinLitTrans"),
    LITERALLINLITDIVISA("LiteralLinLitDivisa"),
    CURRENCY_CHANGE_AMOUNT("currency_change_amount"),
    LITERALLINMARCA("LiteralLinMarca"),
    LINMARKUP("linMarkUp"),
    LINLITCOMISION("linLitComision"),
    LITERALLINLITENTIDAD("LiteralLinLitEntidad"),
    LITERALLINCAMBIO("LiteralLinCambio"),
    RESTLITERALS("RestLiterals"),
    LINLITINF("linLitInf"),
    AUTHENTICATION_SECTION("authentication_section"),
    PIN_AUTHENTICATION("pin_authentication"),
    FROM_DATE_LABEL("from_date_label"),
    FROM_DATE("from_date"),
    TO_DATE("to_date"),
    TO_DATE_LABEL("to_date_label"),
    OPERATION_LIST("operation_list"),
    CURRENT_PAGE("current_page"),
    TOTAL_PAGES("total_pages"),
    TPV_LABEL("tpv_label"),
    TPV_NUMBER("tpv_number"),
    SINGLE_OPERATION("singleOperation"),
    OPERATION_DATE("operationDate"),
    OPERATION_TIME("operationTime"),
    ORDER_ID("orderID"),
    SINGLE_OPERATION_TYPE("operationType"),
    OPERATION_RESULT("operationResult"),
    AMOUNT("amount"),
    CURRENCY_FOR_SINGLE_OPERATION("currency"),
    CARD_NUMBER_FOR_SINGLE_OPERATION("cardNumber"),
    AUTH_NUMBER_FOR_SINGLE_OPERATION("authorizationNumber"),
    REFERENCE("reference"),
    AUTH_NUMBER("authorization_number"),
    SIGNATURE_AUTHENTICATION("signature_authentication"),
    SIGNATURE_LABEL("signature_label"),
    ENT_LABEL("ent_label"),
    ENT_NUMBER("ent_number"),
    AUTHORIZATIONS_AMOUNT("auth_amount"),
    MERCHANT_NUMBER_LABEL("merchant_number_label"),
    AUTHORIZATIONS_NUM_OF_OPERATIONS("auth_num_operations"),
    PRE_AUTHORIZATIONS_AMOUNT("pre_auth_amount"),
    PRE_AUTHORIZATIONS_NUM_OF_OPERATIONS("pre_auth_num_operations"),
    REFUNDS_AMOUNT("refunds_amount"),
    REFUNDS_NUM_OF_OPERATIONS("refunds_num_operations"),
    CONFIRMATIONS_AMOUNT("confirmations_amount"),
    CONFIRMATIONS_NUM_OF_OPERATIONS("confirmations_num_operations"),
    DENIED_AMOUNT("denied_amount"),
    DENIED_NUM_OF_OPERATIONS("denied_num_operations"),
    TOTALS_AMOUNT("total_amount"),
    AUTHS("auth"),
    PREAUTHS("preauth"),
    REFUNDS("refunds"),
    CONFIRMATION("confirmations"),
    TOTALS_NUM_OF_OPERATIONS("total_num_operations"),
    CURRENCY_VALUE("currency_value"),
    AUTH_LABEL("authorization_label"),
    CURRENCY_LABEL("currency"),
    TPV("tpv"),
    ORIGINAL_ORDER_LABEL("original_order_label"),
    ORIGINAL_ORDER("original_order"),
    REFERENCE_LABEL("reference_label"),
//    TICKET_CLOSING_MESSAGE("ticket_closing_message"),
    TICKET_LOGO("ticket_logo");


    private String id;

    HtmlIDs(String id)
    {
        this.id = id;
    }

    public String getId()
    {
        return id;
    }
}